import type { Script } from "./Scripts"
import type { StatName } from "./Stats"
import type { Player } from "./Player"
import type { Game } from "./Game"
import { createRegistry } from "../utils/registry"

export type CardId = string
export type CardType = 'Quest' | 'Effect' | 'Trait' | 'Task' | 'Access' | 'Date'

/** A transient reminder generated by a card's reminders hook. */
export interface Reminder {
  text: string
  urgency: 'info' | 'warning' | 'urgent'
  cardId?: CardId
  /** Optional tooltip detail shown on hover. */
  detail?: string
}

// Mutable data for a card, used for serialization
export interface CardData {
  id?: CardId
  type?: CardType
  // Additional instance-specific properties can be added here
  [key: string]: unknown
}

// Static / library information for a card
export interface CardDefinition {
  name: string
  description?: string
  /** Dynamic name based on card instance data. Falls back to static `name` if omitted. */
  displayName?: (card: Card) => string
  /** Dynamic description based on card instance data. Falls back to static `description` if omitted. */
  displayDescription?: (card: Card) => string
  image?: string
  type: CardType
  script?: Script
  condition?: Script
  afterUpdate?: Script
  calcStats?: (player: Player, card: Card, stats: Map<StatName, number>) => void
  /** Generate transient reminders for this card (timetable entries, deadlines, etc.). */
  reminders?: (game: Game, card: Card) => Reminder[]
  /** Display colour for this card (used in UI for effect tags, debug buttons, etc.). */
  colour?: string
  /** Card IDs that this card replaces (removed when this card is added). */
  replaces?: CardId[]
  /** Card IDs that subsume this card (this card is not added if any are present). */
  subsumedBy?: CardId[]
  /** When true, multiple instances of this card can coexist. Default is false (self-subsuming). */
  allowMultiple?: boolean
  /** Called during time passage. Receives elapsed seconds since last tick. */
  onTime?: (game: Game, card: Card, seconds: number) => void
  // Additional definition properties can be added here
  [key: string]: unknown
}

// Card definitions registry
const cardRegistry = createRegistry<CardDefinition>('Card')

/** Represents a game card instance with mutable state. Definitional data is accessed via the template property. */
export class Card {
  id: CardId
  type: CardType
  /** Whether this card has been completed (quests, dates, tasks). */
  completed: boolean
  /** Whether this card has failed (quests, dates, tasks). */
  failed: boolean
  // Additional instance-specific properties (content-authored)
  [key: string]: unknown

  constructor(id: CardId, type: CardType) {
    this.id = id
    this.type = type
    this.completed = false
    this.failed = false
  }

  /** Read a numeric custom property (returns 0 if absent/non-numeric). */
  num(key: string): number {
    const v = this[key]
    return typeof v === 'number' ? v : 0
  }

  /** Gets the card definition template. */
  get template(): CardDefinition {
    return cardRegistry.getOrThrow(this.id)
  }

  /** Standard fields that are serialised explicitly (not via the generic property loop). */
  private static readonly KNOWN_KEYS = new Set(['id', 'type', 'completed', 'failed', 'template'])

  toJSON(): CardData {
    const data: CardData = {
      id: this.id,
      type: this.type,
      completed: this.completed,
      failed: this.failed,
    }

    // Include content-authored custom properties
    Object.keys(this).forEach(key => {
      if (!Card.KNOWN_KEYS.has(key)) {
        data[key] = this[key]
      }
    })

    return data
  }

  static fromJSON(json: string | CardData): Card {
    const data = typeof json === 'string' ? JSON.parse(json) : json
    const cardId = data.id
    const cardType = data.type
    
    if (!cardId) {
      throw new Error('Card.fromJSON requires an id')
    }
    
    if (!cardType) {
      throw new Error('Card.fromJSON requires a type')
    }
    
    // Verify definition exists
    cardRegistry.getOrThrow(cardId)

    // Create card instance and restore standard fields
    const card = new Card(cardId, cardType)
    card.completed = !!data.completed
    card.failed = !!data.failed

    // Apply content-authored custom properties
    Object.keys(data).forEach(key => {
      if (!Card.KNOWN_KEYS.has(key)) {
        card[key] = data[key]
      }
    })
    
    return card
  }
}

// Get a card definition by id
export function getCard(id: CardId): CardDefinition | undefined {
  return cardRegistry.get(id)
}

/** Return all registered definitions of a given type, as [id, definition] pairs. */
export function getCardDefinitions(type: CardType): [CardId, CardDefinition][] {
  return Object.entries(cardRegistry.getAll())
    .filter(([, def]) => def.type === type) as [CardId, CardDefinition][]
}

// Export for use in story files
export function registerCardDefinition(id: CardId, definition: CardDefinition): void {
  cardRegistry.register(id, definition)
}
